### PR TITLE
add Unattended-Upgrade::Origins-Pattern

### PR DESCRIPTION
**Pull request by le9i0nx**

### CODE REVIEW

**Comment by drybjed** [comment]
The result seems to be wrong on Ubuntu:
```
origin=Debian,codename=precise,label=Debian-Security
```
You would probably need to add at least `ansible_distribution` here, not sure what label is used on Ubuntu systems for this repository.

**Comment by le9i0nx** [comment]
it is very difficult to realize in the universal line

**Comment by drybjed** [comment]
Sounds like it worked. :-)

**Comment by le9i0nx** [comment]
I looked at the log in unattended upgrades on ubuntu.
Properly should somehow be so.
https://github.com/le9i0nx/ansible-apt/commit/f86fdf9bf8bb52f18d49b960ed13335cd9ab661e

**Pull request merged**
